services:
  - type: web
    name: soulmate-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        value: 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
      - key: SUPABASE_URL
        value: https://iywsdqzgvmxxohmawjmo.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5d3NkcXpndm14eG9obWF3am1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyODU3NzksImV4cCI6MjA1NTg2MTc3OX0.di8Qy5oeN-u3L6keO60pGv8tCO_l83UAHFUex-ynoVg
      - key: SUPABASE_JWT_SECRET
        value: 3NpaT2WSjW/eE3eIg+LLiO2zaLrJ+fT011qQStqx8Bka12sZJb90wli/bzOLxkOZL5LPIyRImaOryiHxelnwjg==
